<%!
from alembic import util
%>
"""A generic template used by Alembic for rendering migrations."""

"""Do not edit this file unless you know what you are doing."""

from alembic import op
import sqlalchemy as sa

def upgrade():
    pass

def downgrade():
    pass
